### 1 - add a new user
POST http://localhost:3000/users/addUser
Content-Type: application/json

{ 
    "username": "Rahul",
    "gender": "M",
    "age": 35
}
### 2 - get all users
GET http://localhost:3000/users

### 3 - add user vehicle
POST  http://localhost:3000/users/addUserVehicle
Content-Type: application/json

{
    "username": "Rahul",
    "vehicle_brand": "XUV",
    "vehicle_number": "KA-05-1234"
}

### 4 - offer a new ride
POST  http://localhost:3000/offer-ride/offerRide
Content-Type: application/json

{
    "username": "Rohan",
    "origin": "Bangalore",
    "destination": "Pune",
    "available_seats": 1,
    "vehicle": "Swift, KA-01-12345"
}

### 5 - Find a Ride for a User
POST  http://localhost:3000/offer-ride/findRide
Content-Type: application/json

{
    "username": "Gaurav",
    "origin": "Bangalore",
    "destination": "Mysore",
    "seats": 1,
    "preferred_vehicle": "Activa"
}

# {
#     "username": "Nandini",
#     "origin": "Bangalore",
#     "destination": "Mysore",
#     "seats": 1,
#     "preferred_vehicle": "Most Vacant"
# }


### 6 - End a Ride for
POST  http://localhost:3000/offer-ride/endRide
Content-Type: application/json

{
    "username": "Gaurav",
    "origin": "Bangalore",
    "destination": "Mysore",
    "vehicle": "Activa KA-12-12332"
}